### ISSUE TITLE
Two Sets

### ISSUE THREAD

**Issue by Amandeep603** [Amandeep603/CSES-Question#2]
Your task is to divide the numbers 1,2,…,n into two sets of equal sum.

Input
The only input line contains an integer n.

Output
Print "YES", if the division is possible, and "NO" otherwise.

After this, if the division is possible, print an example of how to create the sets. First, print the number of elements in the first set followed by the elements themselves in a separate line, and then, print the second set in a similar way.

Constraints
1≤n≤10^ 6
 
Example 1
Input:

7
Output:
YES
4
1 2 4 7
3
3 5 6

Example 2
Input:
6
Output:
NO

**Comment by AvinashAnand02** [comment]
`import java.util.ArrayList;
import java.util.List;
import java.util.Scanner;

public class EqualSumDivision {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        int n = scanner.nextInt();

        if (n % 4 == 0) {
            System.out.println("YES");
            int sum1 = n / 4;
            int sum2 = n / 4;
            List<Integer> set1 = new ArrayList<>();
            List<Integer> set2 = new ArrayList<>();

            for (int i = 1; i <= n; i++) {
                if (i <= n / 2) {
                    if (set1.size() < sum1) {
                        set1.add(i);
                    } else {
                        set2.add(i);
                    }
                } else {
                    if (set2.size() < sum2) {
                        set2.add(i);
                    } else {
                        set1.add(i);
                    }
                }
            }

            System.out.println(set1.size());
            for (int num : set1) {
                System.out.print(num + " ");
            }
            System.out.println();

            System.out.println(set2.size());
            for (int num : set2) {
                System.out.print(num + " ");
            }
        } else {
            System.out.println("NO");
        }
    }
}
`

**Comment by AvinashAnand02** [comment]
!assign
